IR: turn some IR nodes into data classes
chipsalliance/firrtl pull request #2071
Opened 2021-02-03 17:21 UTC by ekiwi

As discussed with @jackkoenig , I am changing Stop, Print and Verification to be a data class.
This is done in preparation for a new `name` field in order to preserve backwards compatibility.

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- code refactoring

#### API Impact

- it should maintain the current API

#### Backend Code Generation Impact
- none

#### Desired Merge Strategy

- squash

#### Release Notes

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

2021-02-03 18:01 UTC, chick approved these changes
This looks pretty straightforward to me. 
The @data provided constructor seems to confuse IntelliJ a bit but things compile and run.
You should probably wait for second review from @jackkoenig before merging

2021-02-03 18:10 UTC, ekiwi commented
>  The @DaTa provided constructor seems to confuse IntelliJ a bit but things compile and run.

Yes. That is somewhat annoying.



>  You should probably wait for second review from @jackkoenig before merging

I especially would like @jackkoenig to check if there is a way to simplify the additions to the `build.sbt`.

2021-02-03 22:37 UTC, jackkoenig commented
As an experiment, I went ahead and backported this and checked binary compatibility against 1.4.2, here were the errors:
```
firrtl: Failed binary compatibility check against edu.berkeley.cs:firrtl_2.12:1.4.2! Found 12 potential problems
 * class firrtl.ir.Print is declared final in current version
   filter with: ProblemFilters.exclude[FinalClassProblem]("firrtl.ir.Print")
 * static method tupled()scala.Function1 in class firrtl.ir.Print does not have a correspondent in current version
   filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("firrtl.ir.Print.tupled")
 * static method curried()scala.Function1 in class firrtl.ir.Print does not have a correspondent in current version
   filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("firrtl.ir.Print.curried")
 * the type hierarchy of object firrtl.ir.Print is different in current version. Missing types {scala.runtime.AbstractFunction5}
   filter with: ProblemFilters.exclude[MissingTypesProblem]("firrtl.ir.Print$")
< and the same for Verification and Stop >
```
These are all good overall, and it should be binary compatible for adding new fields going forward, but it's a bit of a bummer that we can't easily switch to `@data` on a minor version without breaking binary compatibility.

2021-02-03 22:53 UTC, jackkoenig requested changes
build.sbt changes look good; it's the best way to express macros in 2.13 and 2.12 that I've come across.

I have a few requested changes though.

2021-02-03 22:53 UTC, jackkoenig commented on build.sbt
> +    "io.github.alexarchambault" %% "data-class" % "0.2.1",
```suggestion
    "io.github.alexarchambault" %% "data-class" % "0.2.5",
```

2021-02-03 22:53 UTC, jackkoenig commented on src/main/scala/firrtl/ir/IR.scala
> +  def unapply(s: Stop): Option[(Info, Int, Expression, Expression)] = {
```suggestion
  def unapply(s: Stop): Some[(Info, Int, Expression, Expression)] = {
```

This is not something I knew until just today I happened to see a conversation about it on Gitter. In Scala 2.13.4 you'll get an exhaustivity warning unless you return the more specific type: See https://github.com/scodec/scodec/pull/296 and the linked Gitter conversation.

2021-02-03 22:53 UTC, jackkoenig commented on src/main/scala/firrtl/ir/IR.scala
> +  def unapply(s: Print): Option[(Info, StringLit, Seq[Expression], Expression, Expression)] = {
```suggestion
  def unapply(s: Print): Some[(Info, StringLit, Seq[Expression], Expression, Expression)] = {
```

2021-02-03 22:53 UTC, jackkoenig commented on src/main/scala/firrtl/ir/IR.scala
> +  def unapply(s: Verification): Option[(Formal.Value, Info, Expression, Expression, Expression, StringLit)] = {
```suggestion
  def unapply(s: Verification): Some[(Formal.Value, Info, Expression, Expression, Expression, StringLit)] = {
```

2021-02-03 23:05 UTC, davidbiancolin commented
Is there an issue that provides more context for this? Could it be linked in the PR?

2021-02-03 23:18 UTC, ekiwi commented
> Is there an issue that provides more context for this? Could it be linked in the PR?

This PR followed from a discussion we had on the UCB-BAR slack in the `chisel-dev` channel.
The most important advantage of `data` classes vs. `case` classes is that `data` classes do not define `unapply` and `copy` methods which are hard/impossible to keep backwards compatible when adding a new field.

2021-02-03 23:20 UTC, jackkoenig commented
> Is there an issue that provides more context for this? Could it be linked in the PR?

I'm not sure that there is so we might as well make it here.

Basically, case classes are terrible for binary compatibility if you need to add another field. Adding a field breaks binary compatibility for the `copy` and `unapply` methods. I believe if you implement the `copy` method yourself, the Scala compiler will *not* generate one for you. I think the same is supposed to occur for `unapply`, but I think that is broken in Scala 2.12 despite release notes for [Scala 2.12.12 saying it should work](https://github.com/scala/scala/releases/tag/v2.12.2), here's proof showing it doesn't work in 2.12.12 https://scastie.scala-lang.org/MlNqn8ClQWalnUuZGuZocw (h/t @ekiwi).

2021-02-03 23:48 UTC, davidbiancolin commented
Great, thanks @ekiwi & @jackkoenig. And this is in preparation for #2057, which presumably would make it possible to annotate those statements? (Sorry for the tangent.)

2021-02-03 23:52 UTC, jackkoenig commented
> Great, thanks @ekiwi & @jackkoenig. And this is in preparation for #2057, which presumably would make it possible to annotate those statements? (Sorry for the tangent.)

Exactly. I think there's a debate to be had if we should use `@data` for everything, or only opportunistically whenever we want to add fields. This is at least letting Kevin do what he wants to accomplish while we mull over the larger policy decision.

One very unfortunate thing is that Scala 3 does not support macro annotations so we will have to use a different approach once we get there, but since the whole "unapply" generation thing is fixed in Scala 2.13, it's probably fixed in Scala 3 as well so presumably we can just use case classes with careful migration.

2021-02-04 01:51 UTC, jackkoenig approved these changes
LGTM

2021-02-04 01:56 UTC, merged