Implement MFC-style source locator compression
chipsalliance/firrtl pull request #2212
Opened 2021-05-03 23:07 UTC by jared-barocsi

### Contributor Checklist

#### Type of Improvement

code refactoring

#### API Impact

No impact

#### Backend Code Generation Impact

This only affects the commented source locators in the generated Verilog code. No functional impact.

#### Desired Merge Strategy

Squash

#### Release Notes

Implement MFC-style locator compression in SFC, to reduce redundancy in source locator comments

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

2021-05-04 16:17 UTC, seldridge commented
@jared-barocsi: This looks cool. Can you run an `sbt scalafmtAll` on this? (The reason why CI is failing.)

2021-05-04 16:44 UTC, ekiwi requested changes
Thanks for this PR. There are a couple of things that need to be done, before we can merge it:

1) this needs a couple of unit-tests that fail without this feature and pass once you add it.
2) it seems like this would actually fail if you use the source locator format that we currently have in the firrtl spec:
![Screenshot from 2021-05-04 09-41-05](https://user-images.githubusercontent.com/2456545/117038766-e1612000-acbc-11eb-873d-428601b56135.png)

So you would at least have to update the spec to contain the format that you are assuming here and clarify that this format will be required from now on.

On that note: it there a reason you decided to just parse the string inside the `split` function? Are you expecting a use-case, where people use "non-conforming" file-info strings and just never call the `split` function? If we start requiring a certain format for file-info strings (which I am in favor of!) we might want to consider doing that parsing as part of the firrtl-ir parser and then we could keep that information as `file`, `line`, `column` inside the IR node.
What do you think?

2021-05-04 19:26 UTC, jared-barocsi commented
@ekiwi:

My impression with this compression algorithm is that it would be another step to conduct when emitting Verilog in particular. The issue was introduced to me as the existing .v output containing a lot of redundancy in its source locators, as compared to another approach that tries to reduce this redundancy as much as possible. As such, I assumed that all of these file-infos will always be in the form of `{file.scala} {line number}:{column number}` because they would be automatically generated while compiling Scala code into Verilog.

As for `split`, I mainly wanted a clean-looking function that would split the file name, line number and column number from the String and return these as a tuple, and it made sense for it to be entirely contained within `FileInfo`. But I agree that this issue would be better addressed with a proper data structure rather than parsing a wrapped String. Perhaps I should do some work in a separate PR to upgrade the firrtl spec and turn `FileInfo` into the data structure we would want first?

2021-05-04 20:05 UTC, ekiwi commented
> As such, I assumed that all of these file-infos will always be in the form of `{file.scala} {line number}:{column number}` because they would be automatically generated while compiling Scala code into Verilog.

We would like to be able to convert any "valid" firrtl to Verilog. So if your `flatten` function gets called by default when emitting Verilog, that would probably fail.

One good way to test this would be to add a unittest that takes the example firrtl from the spec that I posted above and to just translate it to Verilog. That way we can see if your new implementation of `flatten` will blow up on that kind of firrtl.

2021-05-12 22:58 UTC, jared-barocsi commented
@ekiwi, I've made some changes to how greedily the algorithm tries to compress these FileInfos. Now, it only does it to any FileInfo which matches the "file line:col" format, and otherwise it simply passes over any other FileInfos that don't meet that criteria. Thus, all valid firrtl code should compile now - for instance, I've added a test that uses the FileInfo format in the firrtl spec, and the algorithm is capable of ignoring it.

Most of this work might end up being technical debt as I think FileInfos having their own structure makes sense.

2021-05-12 23:10 UTC, ekiwi requested changes
Looks good to me, but before we merge this I have a question:

1) Is this compression supposed to only be used in the Verilog emission, or also when serializing Firrtl?
  a) if the answer is no, it would be great if you could add a test that makes sure that when serializing to Firrtl, the file info is not changed
  b) if the answer is yes, then you need to make sure that your algorithm can deal with its own output since someone might serialize to firrtl, parse the generated firrtl string and then try to generate Verilog

2021-05-13 17:15 UTC, jared-barocsi commented
I believe the algorithm acts whenever the firrtl gets serialized in some way. I've added a test to simply check if the algorithm ignores its own output, which it should if it doesn't match the regular expression.

2021-05-13 20:04 UTC, ekiwi approved these changes
LGTM

2021-05-13 21:30 UTC, merged

2021-06-02 20:25 UTC, ekiwi commented
>     1. a) if the answer is no, it would be great if you could add a test that makes sure that when serializing to Firrtl, the file info is not changed

turns out that the info is actually changed when serializing: https://github.com/chipsalliance/firrtl/pull/2253