Avoid using self reference to signal no init
chipsalliance/firrtl pull request #2473
Opened 2022-01-25 01:54 UTC by Andful

This fixes the bug in issue #2449.  
I thought these changes may or may not come in useful given the discussion in the issue so I decided to just let you decide and put this pull request here.  
But if there is an interest in supporting `useInitAsPreset` I am willing to make further adjustments and add a test.

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you update the FIRRTL spec to include every new feature/behavior?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

#### API Impact

#### Backend Code Generation Impact

#### Desired Merge Strategy

#### Release Notes

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

2022-01-25 21:46 UTC, jackkoenig commented
@sequencer can you take a look at this?

2022-01-25 22:05 UTC, sequencer commented
Sure! I think this should be a bug fix(which might block 3.5.1) I will take a look at this today.

2022-01-25 22:56 UTC, jackkoenig requested changes
Actually I don't think this is right. A self-initialization value is the canonical way within the FIRRTL IR to mean "no reset" so it shouldn't be changed. If there is a bug here, it's in emitters misinterpreting that.

2022-01-26 08:46 UTC, johnsbrew commented
As far as I understand, there is no bug here, only related to https://github.com/chipsalliance/firrtl/pull/2449#issuecomment-1020595519

(anyone to have a look at #2468 btw ?)

2022-01-26 11:18 UTC, Andful commented
> Actually I don't think this is right. A self-initialization value is the canonical way within the FIRRTL IR to mean "no reset" so it shouldn't be changed. If there is a bug here, it's in emitters misinterpreting that.

Yes I did notice that. I think using reset as the "0" literal would be a more elegant solution. Both `useInitAsPreset` and `PresetRegAnnotation` rely on the `init` value as a preset.  
This becomes a problem when you have a register to both have a preset and a possibly a reset signal (which is the case for `useInitAsPreset`). If the compiler notices that there is no reset it will modify `init` which also is its preset value.

2022-01-26 12:01 UTC, Andful commented
But I don't know how involved would be to use the literal "0" to signal no reset. From what I saw only `RtlilEmitter` and `VerilogEmitter` rely on it.

2022-01-26 15:28 UTC, Andful commented
@johnsbrew The bug is not user facing. The bug is that the class [`CustomDefaultRegisterEmission`](https://github.com/chipsalliance/firrtl/blob/b027eb466b033a0a9d229f19feb931ddb292a9fa/src/main/scala/firrtl/EmissionOption.scala#L15) has an option `useInitAsPreset` which does not make sense if the compiler changes `init` if it sees that a register is never resetted.

2022-01-26 16:27 UTC, ekiwi commented
> But I don't know how involved would be to use the literal "0" to signal no reset. From what I saw only `RtlilEmitter` and `VerilogEmitter` rely on it.

There are other passes that rely on this. For example some of my own passes use the `init` value to see if the register has an init value or not.

> @johnsbrew The bug is not user facing. The bug is that the class [`CustomDefaultRegisterEmission`](https://github.com/chipsalliance/firrtl/blob/b027eb466b033a0a9d229f19feb931ddb292a9fa/src/main/scala/firrtl/EmissionOption.scala#L15) has an option `useInitAsPreset` which does not make sense if the compiler changes `init` if it sees that a register is never resetted.

If the register is properly connected to a reset that is marked with the `PresetAnnotation`, then the compiler will keep the `init` value around. The same is true for async registers. Only for synchronous reset / no reset registers will `init` be replaced with a reference to the register.

2022-01-26 16:30 UTC, ekiwi commented
@Andful : Do you have a concrete example of a Chisel circuit that could demonstrate the bug you are trying to fix? I am not quite sure what the problem is and maybe, once we all understand what exactly the behavior is that you are trying to change, we can think of a better way to solve this.

2022-01-26 17:07 UTC, Andful commented
@ekiwi The example in the pull request #2449. That was the very reason why `useInitAsPreset` was set to `false`.

2022-01-26 17:08 UTC, ekiwi commented
> @ekiwi The example in the pull request #2449. That was the very reason why `useInitAsPreset` was set to `false`.

But #2449 fixed that bug, no?

2022-01-26 17:19 UTC, Andful commented
I mean, the bug is not user facing anymore but if you set `useInitAsPreset` to true it might emit malformed verilog. If `init` is possibly self referencing at any time `useInitAsPreset` should never be set to true.

2022-01-26 17:20 UTC, ekiwi commented
> I mean, the bug is not user facing anymore but if you set `useInitAsPreset` to true it might emit malformed verilog. If `init` is possibly self referencing at any time `useInitAsPreset` should never be set to true.

Could we fix this maybe by removing the `useInitAsPreset` option from the constructor? It seems to me like it sneaked into an unrelated PR and maybe should never have ended up there.

2022-01-26 17:27 UTC, Andful commented
> > I mean, the bug is not user facing anymore but if you set `useInitAsPreset` to true it might emit malformed verilog. If `init` is possibly self referencing at any time `useInitAsPreset` should never be set to true.
> 
> Could we fix this maybe by removing the `useInitAsPreset` option from the constructor? It seems to me like it sneaked into an unrelated PR and maybe should never have ended up there.

Yes. But generally I think a preset is useful information for a circuit.

2022-01-26 17:29 UTC, sequencer commented
In my understanding:
**the semantic of `Preset` is register/memory state before reset.**
So there will be 3 different options each preset:
1. Preset to 1
2. Preset to 0
3. Random

Current implementation to Preset is adding an `initial` field(defined IEEE1364-2005: 9.9.1 Initial construct) but don't use `#` to construct delay, and so does `RANDOMIZE`.
So I think we cannot have both random and preset in the same time.

So the issue becomes:
we can disable random and set preset a register, but this seems to be an Emitter bug.

2022-01-26 17:30 UTC, ekiwi commented
> Yes. But generally I think a preset is useful information for a circuit.

We do have a way to make registers with a "preset" and that is to use the `PresetAnnotation`. I don't think we ever intended to support an alternative way. https://github.com/chipsalliance/firrtl/pull/2396 was supposed to allow users to disable the randomization logic and was not intended to change anything about "preset" registers.

2022-01-26 17:31 UTC, sequencer commented
> #2396 was supposed to allow users to disable the randomization logic and was not intended to change anything about "preset" registers.

Actually random is another type of "preset", so both "preset" and "random" is not possible.

2022-01-26 17:35 UTC, sequencer commented
Doesn't define the preset value, https://scastie.scala-lang.org/ZRHZGEs1TsGoIdku7niUog, if it is defined, will it behave correctly? @ekiwi 
If true, I think we only need add some logic to emitter: 
if a register is preset, we should disable random for it, and assert the preset value exist.

2022-01-26 18:46 UTC, Andful commented
@sequencer In this [example](https://scastie.scala-lang.org/XWRlEiEHRjuHYIUgQjbBbQ) (provided by @jackkoenig) does not initialize `context`as random so I would say it is working correctly. So I guess currently only `useInitAsPreset` is dubious and should be removed.

2022-01-26 20:44 UTC, closed without merging

2022-01-27 10:10 UTC, johnsbrew commented
@Andful 

### A bit of context about `Reset`, `AsyncReset` and `Preset`

I do understand your point, the main issue you raise here is that firrtl does not consider preset as first class citizen.
For the record I was in favor of such an approach when I initially proposed the support of these presets #991 

After discussion, @jackkoenig & @seldridge point of view was the following:
- chisel is aimed at providing 100% re-usable hardware generators
- preset are a FPGA-only feature *(also meaningful in simulation)*
- hence, preset cannot be a first class citizen alongside synchronous and asynchronous resets 

It was then decided to provide an implementation of preset (which is the current version) based on annotating AsyncReset
- convienient because AsyncResets already enforce static init values
- *de facto* preventing the ability to use multiple resets for the the same register.

As of today, there is for example no way to generate the following verilog, and this is unlikely to happen anytime soon.
```verilog
    reg triple_reset = <preset_init>;
    always @ (posedge clock or areset) begin
      if (areset) begin
        triple_reset <= <async_init>;
      end else begin
        if (sreset) begin
          triple_reset <= <sync_init>;
        end else begin
          triple_reset <= normal_value;
        end
      end
    end

```
Note that the main restriction is the incompatibility of `AsyncReset` with `Preset`, as synchronous resets can always be written in plain Chisel:

```scala
class Async(forcePreset: Boolean=false) extends Module with RequireAsyncReset {
  val sreset = IO(Input(Bool())) 

  val i = IO(Input(Bool()))
  val o = IO(Output(Bool())) 

  val r = RegInit(false.B)
  when(sreset) {
    r := true.B
  } .otherwise {
    r := i
  }
  o := r

  // then, one might want to convert AsyncReset to Preset
  if(forcePreset) {
    annotate(new ChiselAnnotation {
      def toFirrtl = firrtl.annotations.PresetAnnotation(reset.toTarget)
    }) 
  }
}
```
see https://scastie.scala-lang.org/z6Ch0u5ASueDaTTbacjhCQ for resulting verilog

### `EmissionOptions` trait vs `--emission-options=` command-line

I first introduced `EmissionOptions`with `useInitAsPreset` and `disableRandomization` in #1050 
https://github.com/chipsalliance/firrtl/pull/1050/files#diff-acc9dea5ae74bda279f6f83be79e549dba609d7ac04306426395f0dccd693e16

It was an attempt to partially customized the emission, intended to be used by transforms adding annotations.
Theses options add 2 features on register emission
- `useInitAsPreset` => used to convert an asynchronously reset RegInit into a preset RegInit
- `disableRandomization` => used to remove the random initialization statements (based on initial begin)

Out of 4 combinations of these 2 flags, only 3 are meaningful
- `!useInitAsPreset & !disableRandomization` => default behavior
- `useInitAsPreset & disableRandomization` => Emit proper Preset
- `disableRandomization` => deactivate randomization

This API is an advanced transform API, with local effect (only one register is concerned by each annotations) and it has in fact little to do with the newer `--emission-options=` available from the command line since  #2396 
This command-line API sets **default values** for the above mentioned flags.
While it makes sense for disabling randomization at circuit scale (kind of cosmetic), it certainly doesn't for using init as preset at this scale.
Indeed,  except for small designs,  various reset trees must be preserved and only preset-annotated resets shall result in `RegInit` using init as preset: this is precisely how ` firrtl.annotations.PresetAnnotation(reset.toTarget)` works behind the scene.
 
> So I guess currently only useInitAsPreset is dubious and should be removed.

While your conclusion about `useInitAsPreset` makes sense from a command-line point of view (where it should never have ended up alongside `disableRegisterRandomization`), it is in fact very useful as `EmissionOptions` 😃 

Hope this helps to understand the big picture, even if I'm not sure anyone will read this long comment 😅