Fix optimization of register with reset but invalid connection
chipsalliance/firrtl pull request #2520
Opened 2022-04-21 22:44 UTC by jackkoenig

Fixes #2516

Previously,
```
reg r : UInt<8>, clock with :
  reset => (p, UInt<8>(3))
r is invalid
```
would compile to:
```
reg r : UInt<8>, clock
r <= UInt<8>(0)
```
now it compiles to:
```
reg r : UInt<8>, clock
r <= UInt<8>(3)
```

### Contributor Checklist

- [NA] Did you add Scaladoc to every public function/method?
- [NA] Did you update the FIRRTL spec to include every new feature/behavior?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

 - bug fix        

#### API Impact

This is a 

#### Backend Code Generation Impact

No impact

#### Desired Merge Strategy

 - Squash

#### Release Notes

Fix lowering of synchronously reset registers that have an invalid connection.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

2022-04-21 22:57 UTC, ekiwi approved these changes
:shipit:

2022-04-21 22:57 UTC, ekiwi commented
Needs some `scalafmtAll` though

2022-04-21 23:15 UTC, seldridge requested changes
(I spoke to Jack about this separately.)

I don't think the additional invalid interpretation here is correct or self-consistent with existing SFC behavior. The end-to-end compile of this should result in a mux with zero, not optimization to the reset value. My reasoning is that this pass is narrowly responsible for moving the reset mux in front of the register. Any further optimization should not happen and is introducing yet-another-interpretation of invalid that has to be special cased.

Put differently, this creates a reset `mux` not a reset `when`. I would expect the pass to generate or be equivalent to the following:

```scala
    reg r : UInt<8>, clock
    wire inv: UInt<8>
    inv is invalid
    r <= mux(p, UInt<8>(3), inv)
```

2022-04-22 00:49 UTC, jackkoenig commented
Changed it to what @seldridge said. The implementation is a bit uglier, but it is consistent with the behavior when the register has an async reset.

2022-04-22 03:06 UTC, seldridge approved these changes
LGTM

Weakening my previous statements: I would like to revisit the `mux(cond, _, invalid)` canonicalization in the future. It's annoying that this is not unified with `when` or `validif` formulations. Keeping clean separation of lowering (this pass) from optimization/folding will help us better tackle this fully in the future.

2022-04-22 03:20 UTC, merged